version: '2'

services:
  mongodb:
    image: "mongo:3.2.6"
    container_name: mongodb
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-store:/data
    command: -auth
    hostname: mongo-137
    restart: unless-stopped

volumes:
  mongo-store:
